dataset <- read.table("household_power_consumption.txt", sep=";", header = TRUE)
dateTime <- paste(dataset$Date, dataset$Time)
dataset$Date <- as.Date(dataset$Date, "%d/%m/%Y")
dataset$DateTime <- strptime(dateTime, format="%d/%m/%Y %H:%M:%S")
str(dataset)
datePeriod <-as.Date(c('01/02/2007','02/02/2007'), "%d/%m/%Y")
datePeriod
dataset <- dataset[dataset$Date %in% datePeriod ,]
dataset$Global_active_power <- as.numeric(as.character(dataset$Global_active_power))
dataset$Sub_metering_1 <- as.numeric(as.character(dataset$Sub_metering_1))
dataset$Sub_metering_2 <- as.numeric(as.character(dataset$Sub_metering_2))
dataset$Sub_metering_3 <- as.numeric(as.character(dataset$Sub_metering_3))
with(dataset, plot(DateTime, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering"))
with(dataset, lines(DateTime, Sub_metering_1, col="grey"))
with(dataset, lines(DateTime, Sub_metering_2, col="red"))
with(dataset, lines(DateTime, Sub_metering_3, col="blue"))
legend("topright", lwd=2, col=c("grey", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()
